site_name: DOORS Data Cube Overview
site_url: https://doors-cubes.readthedocs.io
repo-url: https://github.com/bcdev/doors-recipes
copyright: Copyright © 2023 by the DOORS Team

theme: readthedocs  # alternative: mkdocs

nav:
  - Home:
    - About DOORS Data Sets: index.md
  - Datasets:
    - List of datasets: datasets/datasets.md

    - CMEMS CHL Black Sea Data Cube: datasets/CMEMS_OC_BS_4.zarr.md
    - CMEMS Salinity daily mean Black Sea Data Cube: datasets/bs-cmcc-sal-rean-d_1653925405736.zarr.md
    - CMEMS SST Black Sea Data Cube: datasets/cmems_SST_BS_SST_L4_REP_OBSERVATIONS_010_022_1653926779692.zarr.md
    - DOORS Hereon Wave Products (2D) - Instantaneous Field Data Cube: datasets/Hereon--WAVES-BSeas4-BS-b20230123_re-sv08.00.md
    - DOORS ISMAR-CNR Western BS Hydro 3D Characterization Data Cube: datasets/west2018_01_01_2020_reg_hydro_0.01.md
    - DOORS ISMAR-CNR Western BS TS 3D Characterization Data Cube: datasets/west2018_01_01_2020_reg_ts_0.01.md
    - DOORS METU BGC nutrients Data Cube: datasets/BlackSea_1d_20160101_20160331_bgc_nut.md
    - DOORS METU BGC phytoplanktons Data Cube: datasets/BlackSea_1d_20160101_20160331_bgc_phyto.md
    - DOORS UPC Dniester Coastal (psi values) Data Cube: datasets/coawst_his_sample_psi.md
    - DOORS UPC Dniester Coastal (rho values) Data Cube: datasets/coawst_his_sample_rho.md
    - DOORS UPC Dniester Coastal (u values) Data Cube: datasets/coawst_his_sample_u.md
    - DOORS UPC Dniester Coastal (v values) Data Cube: datasets/coawst_his_sample_v.md
    - HR-OC coastal monthly Black Sea Data Cube: dataset/hroc-l4m-blk-100m-v1.md

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
