site_name: DOORS Data Cube Overview
site_url: https://doors-cubes.readthedocs.io
repo-url: https://github.com/bcdev/doors-recipes
copyright: Copyright © 2023 by the DOORS Team

theme: readthedocs  # alternative: mkdocs

nav:
  - Home:
    - About DOORS Data Sets: index.md
  - Datasets:
    - List of datasets: datasets/datasets.md

    - CMEMS CHL Black Sea Data Cube: datasets/CMEMS_CHL_1x790x1101_v3.zarr.md
    - CMEMS Salinity daily mean Reanalysis Black Sea Data Cube: datasets/CMEMS_SAL_BS_Reanalysis-1x261x591_v5.zarr.md
    - CMEMS Salinity daily mean Forecast Black Sea Data Cube: datasets/CMEMS_SAL_BS_Forecast-1x274x591_v5.zarr.md
    - CMEMS SST Black Sea Data Cube: datasets/CMEMS_SST_BS_SST_L4_REP_OBSERVATIONS_010_022_1x200x321_v4.zarr.md
    - DOORS Hereon Wave Products (2D) - Instantaneous Field Data Cube: datasets/Hereon--WAVES-BSeas4-BS-b20230123_re-sv08.00.md
    - DOORS ISMAR-CNR Western BS Hydro 3D Characterization Data Cube: datasets/west2018_01_01_2020_reg_hydro_0.01.l-9x503x541.zarr.md
    - DOORS ISMAR-CNR Western BS TS 3D Characterization Data Cube: datasets/west2018_01_01_2020_reg_ts_0.01.l-9x503x541.zarr.md
    - DOORS METU nutrients Data Cube: datasets/BlackSea_1d_20180101_20181231_nut_1x1x210x365_v1.0.zarr.md
    - DOORS METU BGC light Data Cube: datasets/BlackSea_1d_20180101_20181231_bgc_light_v1.0.zarr.md
    - DOORS METU Temperature and Salinity Data Cube: datasets/BlackSea_1d_20180101_20181231_grid_T_v1.0.zarr.md
    - DOORS PML OWT, Water Quality, Calimnos L3 Aggregated product (preliminary) Data Cube: datasets/blacksea-owt-300m-1x1792x1736-1.1.0.md
    - DOORS UPC Dniester Coastal (psi values) Data Cube: datasets/coawst_his_sample_psi.md
    - DOORS UPC Dniester Coastal (rho values) Data Cube: datasets/coawst_his_sample_rho.md
    - DOORS UPC Dniester Coastal (u values) Data Cube: datasets/coawst_his_sample_u.md
    - DOORS UPC Dniester Coastal (v values) Data Cube: datasets/coawst_his_sample_v.md
    - HR OC coastal monthly Black Sea Data Cube: dataset/hroc-l4m-blk-100m-v1.md
    - HR OC coastal daily Black Sea Data Cube: dataset/CMEMS_OC_HR_BS-1x2160x1512_v2.md
    - DOORS Danube Delta Erosion Accretion Dataset: dataset/Danube_Delta_erosion_accretion.zarr_v2.zarr.md
    - DOORS Georgia Coast Dynamics Dataset: dataset/Georgia_coast_dynamic_SAR_v2.md
    - DOORS Romania Coast Dynamics Dataset: dataset/Romania_coast_dynamic_SAR_v2.md
    - DOORS Turkey Coast Dynamics Dataset: dataset/Turkey_coast_dynamic_SAR_v2.md
    - DOORS Kakhovka Dam Flood Extent Dataset: dataset/Kakhovka_Dam_S1_flood_extent_20230609.md
    - DOORS Kakhovka Total Suspended Solids Dataset: dataset/TSS_Kakhovka_dam_v2.zarr.md
    - EMODNET Bathymetry: dataset/Kakhovka_Dam_S1_flood_extent_20230609.md
    - Vessel Routes Density 2019 2024: dataset/vessell_routes_density.zarr.md
  - In-Situ Data:
    - In-Situ Data Conventions: insitu/in-situ_data_conventions.md

markdown_extensions:
  - toc:
      permalink: "#"
      baselevel: 2
  - attr_list
